---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: hbvusu
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/qusp66/hbvu_attic_lab

