---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hbvusu-webapp
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: main
  url: https://github.com/qusp66/hbvu_attic_lab/tree/main/kustomize/apps/hbvusu
